# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2.3.1
    - uses: cachix/install-nix-action@v10
      with:
        nix_path: nixpkgs=channel:nixos-20.03

    # Runs a set of commands using the runners shell
    - name: Rebuild readme.md
      run: ./scripts/mkReadme.sh
    - name: Rebuild design.md
      run: ./scripts/mkDesign.sh
    - name: Push to github
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add --force ./readme.md
        git add --force ./design.md
        git commit -m "updates readme.md" || true
        git push
